# Generated by Django 4.0.5 on 2022-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCShop', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
