# Generated by Django 4.0.5 on 2022-06-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCShop', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
